config_models/__init__.py, requirements/base.in, requirements/base.txt, requirements/dev.txt, requirements/doc.txt, requirements/quality.txt, requirements/test.txt, requirements/travis.txt
The last version failed tests due to outdated/mismatched requirements.
@cpennington @jmbowman Please review.
=> Update versions of requirements via pip-compile.

tox.ini
If there is, for example, a virtualenv setup inside the project's root
directory, running tox will result in errors. This happens due to
py.test trying to execute the tests for the packages inside the
virtualenv.
By explicitly naming the package on which tests should be run, this
problem is mitigated.
Fixes #9
=> Add explicit package name to tox py.test command

.travis.yml, config_models/management/commands/populate_model.py, config_models/models.py, config_models/tests/test_config_models.py, config_models/tests/test_decorators.py, config_models/tests/test_model_deserialization.py, requirements/quality.in, requirements/quality.txt, requirements/test.in, setup.py, tox.ini
**Background:** An effort is being made to move everything from Python 2.7 to 3, including making this repository compatible with both as specified on this JIRA issue: https://openedx.atlassian.net/projects/INCR/issues/INCR-18?filter=allopenissues and these changes aim to do that.
**Studio Updates:** None.
**LMS Updates:** None
Testing: Same ones as before (and have been updated to be compatible with both as well), passing.
=> Fixing compatibility issues with Python3

config_models/models.py, config_models/tests/test_config_models.py
Absent this change, the `current_set` and `with_active_flag` methods will generate queries like
SELECT
(1) AS "is_active",
"config_models_examplekeyedconfig"."id",
"config_models_examplekeyedconfig"."change_date",
"config_models_examplekeyedconfig"."changed_by_id",
"config_models_examplekeyedconfig"."enabled",
"config_models_examplekeyedconfig"."left",
"config_models_examplekeyedconfig"."right",
"config_models_examplekeyedconfig"."user_id",
"config_models_examplekeyedconfig"."string_field",
"config_models_examplekeyedconfig"."int_field"
FROM "config_models_examplekeyedconfig"
WHERE (
config_models_examplekeyedconfig.id IN (
SELECT MAX(id)
FROM config_models_examplekeyedconfig
GROUP BY "left", "right", "user"
)
)
ORDER BY "config_models_examplekeyedconfig"."change_date" DESC
Notice in that …
=> Allow the use of ForeignKey fields as ConfigurationModel KEY_FIELDS

.travis.yml
Use 'quality' which will always exists instead of dango111 which no
longer exists after we added the various DRF shards changing the value
of the TOXENV.
=> Correct the TOXENV we release from.

requirements/base.txt, requirements/dev.txt, requirements/doc.txt, requirements/pip-tools.txt, requirements/quality.txt, requirements/test.txt, requirements/travis.txt
Similar to this PR: https://github.com/edx/devstack/pull/401 , a manual upgrade of `pip-tools` to `3.6.1` was required to fix the auto dependency PRs
=> Bump pip-tools and run make upgrade

.travis.yml, CHANGELOG.rst, Makefile, config_models/__init__.py, config_models/models.py, config_models/utils.py, config_models/views.py, requirements/base.in, requirements/base.txt, requirements/constraints.txt, requirements/dev.txt, requirements/doc.in, requirements/doc.txt, requirements/pip-tools.txt, requirements/quality.txt, requirements/test.in, requirements/test.txt, requirements/travis.txt, setup.py, tests/test_config_models.py, tests/utils.py, tox.ini
ConfigModels have used a Django cache for a long time (memcached in
practice), but a major performance issue is that these values are
sometimes requested hundreds of times during the course of rendering
a request. Memcached roundtrips are fast, but not free, and for some
courseware rendering views, memcached access can account for over 20%
of the transaction time.
The TieredCache from edx-django-utils uses a request-level cache and
Django cache in combination so that it will only reach out to
memcached once for a given config value in a given request.
This commit also introduces other notable changes:
* Version has been bumped to 2.0.0
* edx-django-utils is now a dependency (for TieredCache)
* Tests have been updated to use CacheIsolationTestCase rather than
mocking out the cache. This …
=> Add Request level caching, bump to version 2.0.0

.travis.yml, CHANGELOG.rst, config_models/__init__.py, requirements/base.txt, requirements/constraints.txt, requirements/dev.txt, requirements/doc.txt, requirements/pip-tools.txt, requirements/quality.in, requirements/quality.txt, requirements/test.txt, requirements/travis.txt, setup.py, tox.ini
**Issue:** [BOM-1566](https://openedx.atlassian.net/browse/BOM-1566)
- Changed `python36` with `python38`. 
- Removed `django111`, `django20`, `django21`.
- Removed unnecessary constraints and pinned `pip-tools`.
- updated version to `2.0.1`.
=> Python and Django version update in Travis and Tox

CHANGELOG.rst, config_models/__init__.py, config_models/admin.py, tests/test_admin.py
The `allow_tags` attribute is deprecated in Django 2.0:
https://django.readthedocs.io/en/2.0.x/internals/deprecation.html
As a consequence, "Update" edit links are no longer clickable for admin
models that inherit from ConfigurationModelAdmin.
This will close CRI-189 once a new release of django-config-models is
produced and the dependency is upgraded in edx-platform.
This is for the Juniper release (cc @nedbat).
=> Fix wrongly escaped links in admin view lists

requirements/constraints.txt, requirements/dev.txt, requirements/pip-tools.txt, requirements/travis.txt
tox-battery fix has been merged: https://github.com/signalpillar/tox-battery/pull/26
=> Unpin tox-battery and run requirements upgrade

requirements/base.txt, requirements/constraints.txt, requirements/dev.txt, requirements/doc.txt, requirements/quality.txt, requirements/test.txt, requirements/travis.txt
- Pinned `importlib-metadata==1.7.0` as `version>1.7.0` is causing conflicts for python35 in running `make upgrade`.
=> Pin importlib-metadata==1.7.0 for python35

requirements/constraints.txt, requirements/dev.txt, requirements/doc.txt, requirements/quality.txt, requirements/test.txt, requirements/travis.txt
- `importlib-metadata<2.0.0` was causing conflicts in running `make upgrade` with `python3.5`.
- Unpinned `importlib-metadata` constraint after fixing the issue in https://github.com/pypa/virtualenv/pull/1953 and https://github.com/tox-dev/tox/pull/1682.
=> Unpinned importlib-metadata constraint

config_models/__init__.py
We dropped all usage of six and future imports so this should now be pure python 3.x code.  The last release dropped its
dependency on six but was still referencing six in code which was causing issues.
=> Update version in prep for push to PyPI.

CHANGELOG.rst, config_models/__init__.py, tests/utils.py
The correct import path is:
`common.djangoapps.util.memcache.safe_key`.
This is currently broken on Devstack and
stage.edx.org.
This is related to the [import shims removal](https://github.com/edx/edx-platform/pull/25932).
=> Fix deprecated reference of util.memcache.safe_key

Makefile, requirements/base.txt, requirements/ci.txt, requirements/dev.txt, requirements/doc.txt, requirements/pip-tools.txt, requirements/pip.txt, requirements/quality.txt
[requirements upgrade build](https://build.testeng.edx.org/job/django-config-models-upgrade-python-requirements/103/console) failed due to `--no-index` flag error. 
[pip-tools==6.0.0](https://github.com/jazzband/pip-tools/blob/master/CHANGELOG.md#600-2021-03-12) removed `--index/--no-index` flag from [pip-compile](https://github.com/jazzband/pip-tools/pull/1234) command.
`--index/--no-index` flag was [deprecated](https://github.com/jazzband/pip-tools/pull/1130) in [pip-tools==5.2.0](https://github.com/jazzband/pip-tools/blob/master/CHANGELOG.md#520-2020-05-27) in favor of `--emit-index-url/--no-emit-index-url`.
=> fix: remove --no-index flag from pip-compile command

docs/conf.py
Fixed another bug in the docs configuration that impacted Read the Docs builds but not local builds via tox.  Also removed a redundant argument for a command copied in from the cookiecutter.
=> docs: Fix configuration for RTD builds

.github/workflows/upgrade-python-requirements.yml, requirements/base.txt, requirements/ci.txt, requirements/dev.txt, requirements/doc.txt, requirements/pip.txt, requirements/quality.txt, requirements/test.txt
- Updated review team name from `arbi_bom` to `arbi-bom` to let the upgrade workflow successfully tag the team for review.
- Tested the new workflow by running the upgrade requirements actions against the branch itself. Upgrade PR was created and the team was tagged successfully this time. Merged the upgrade requirements changes in this PR too and closed the original PR https://github.com/edx/django-config-models/pull/186 which failed to tag the team for review.
=> Fix review team in upgrade workflow

CHANGELOG.rst, config_models/__init__.py, config_models/admin.py, config_models/management/commands/populate_model.py, config_models/models.py
'django.utils.translation.ugettext_lazy' is deprecated in favour of 'django.utils.translation.gettext_lazy' and will be removed in Django 4.
=> fix: replace deprecated 'ugettext_lazy' with 'gettext_lazy'

Makefile, config_models/models.py, tests/test_admin.py, tests/utils.py
Updated the upgrade target script to check the compatibility of upgraded pip and pip-tools versions.
For reference, look at this [PR](https://github.com/openedx/edx-repo-health/pull/271) for new check added in edx-repo-health. 
JIRA: https://2u-internal.atlassian.net/browse/BOM-3448
=> fix: Install pip and pip-tools in upgrade script

.github/workflows/ci.yml, config_models/__init__.py, config_models/admin.py, setup.py, tox.ini
1. Add Django 4.2 support
2. Bump the version to '2.4.0'
Ticket ref: https://github.com/edx/upgrades/issues/139
=> Django 4.2 support

CHANGELOG.rst, config_models/models.py, tests/test_config_models.py
**Description**
While replacing `python-memcache` with `pymemcache` [ticket link](https://github.com/edx/edx-arch-experiments/issues/92) we got the following error
```
File "/edx/app/edxapp/edx-platform/xmodule/video_block/video_block.py", line 244, in student_view
fragment = Fragment(self.get_html())
File "/edx/app/edxapp/edx-platform/xmodule/video_block/video_block.py", line 355, in get_html
branding_info = BrandingInfoConfig.get_config().get(user_location)
File "/edx/app/edxapp/edx-platform/lms/djangoapps/branding/models.py", line 54, in get_config
return json.loads(info.configuration) if info.enabled else {}
AttributeError: 'NoneType' object has no attribute 'enabled'
```
The reason of above mentioned error was: `django-config-models` was returning `None`.
Which was then used by …
=> fix: check None before returning config

CHANGELOG.rst, config_models/__init__.py, config_models/urls.py
Fixes compatibility with Django 4.2
=> [Django 4.2]: Fix Django 4.2 compatibility

setup.py
We dropped support for Django 3.2 and added support for Python 3.11 and
12 in recent PRs but we didn't update the classifiers so doing that
here.
Python Upgarde PR: https://github.com/openedx/django-config-models/pull/333
=> docs: Update classifiers to match current state.
